### PR TITLE
Security Teams feature

### PR DESCRIPTION
**Pull request by ondrejvelisek**
+ two bug fixes

### CODE REVIEW

**Comment by ondrejvelisek** [comment]
Change InternalErrorException to SecurityTeamAlreadyExists when security team with the same name already exists
Return null when user is not blacklisted instead of false.

**Comment by ondrejvelisek** [comment]
fix compareTo method in SecurityTeams and rebase to current master

**Comment by ondrejvelisek** [comment]
Update postgre and Oracle DB schema

**Comment by stavamichal** [comment]
Fixed in pull request #953

**Pull request closed without merging**
