### PR TITLE
Fix force propagation

### PR DESCRIPTION
**Pull request by mvocu**
This patchset moves processing of forced propagations into special thread both in dispatcher and engine and leaves out all scheduling/execution intervals present for normal propagations. Forcing the propagation now also restarts currently processing tasks, both SEND and GEN.

### CODE REVIEW

**Comment by mvocu** [comment]
Failed tasks are not reported immediately, they undergo the usual procedure of retry/resubmission (as described by max_retry and delay task parameters) - see PropagationMaintainerImpl::rescheduleErrorTasks(). This is done every two minutes (scheduling cycle for PropagationMaintainer).

**Comment by zlamalp** [comment]
Please update test ``EventParserImplTest.parseEventTest()``. It is checking message format on hardcoded string, but its structure (parser) has changed (added forced flag). Thanks.

**Comment by zlamalp** [comment]
Hi, about "Failed tasks are not reported immediately" you are right. I didn't realize that. Thanks for clarification.

**Comment by mvocu** [comment]
Regarding the "missing" `taskStatus.isTaskFinished()` - this is covered by testing `task.getStatus().equals(cz.metacentrum.perun.taskslib.model.Task.TaskStatus.DONE)`. Status `DONE` is set (in preceding lines) only for tasks that have finished.

**Comment by mvocu** [comment]
The event parser test is updated.

**Comment by zlamalp** [comment]
Thanks for clarification and fixing the test. Otherwise it seems ok, merging.

**Pull request merged**
