### PR TITLE
Transactions - new Auditer Messages behaviour (fixed tests)

### PR DESCRIPTION
**Pull request by jirmauritz**
- PerunConnection created to catch important events such as setSavepoint, releaseSavepoint, rolback
- Auditer Messages are stored in list of lists where inner lists represent one nested transaction
 - when a transaction is successful, all the Auditer Messages from last list are copied to the previous list
 - when a transaction is not successful, the last list is deleted

### CODE REVIEW

**Comment by jirmauritz** [comment]
Core tests are successful with these changes.

**Comment by zlamalp** [comment]
Hi, tests are not ok when real db is in use. They internally call ``Auditer.newTransaction()`` which is not fixed. You can see it on ``AuthzResolverIntegrationTest.isAuthorizedInOtherVo()`` test. I suggest creating method ``getSavepoints()`` which will handle getting of resource from ``TransactionSynchronizationManager``. Please fix also typos in javadoc and method names ``cleanTransation()`` etc. Thanks.

**Comment by jirmauritz** [comment]
Tests should pass with the last commit. Using suggested getSavepoint().

**Comment by zlamalp** [comment]
test all.

**Comment by zlamalp** [comment]
Hi, can you please rebase this branch on current master. There is a fix for test ``FacilitiesManagerEntryIntegrationTest.removeAllFacilityContacts`` which is not passing on real db. Thank you.

**Comment by jirmauritz** [comment]
Rebase on master done.

**Pull request merged**
