### PR TITLE
Table user_ext_source_attr_values was created.

### PR DESCRIPTION
**Pull request by zwejra**
Table user_ext_source_attr_values was added to oracle.sql and postgres.sql.
Changes projected to changelogs oracleChangelog.txt and postgresChangelog.txt.

### CODE REVIEW

**Comment by zlamalp** [comment]
Hi, please remove columns ``user_id integer not null`` and ``ext_source_id integer not null``. Instead use ``ues_id integer not null``. Also please add new table definition to ``schema.sql`` in perun-core module resources (so it's available to in-memory tests).

**Comment by zwejra** [comment]
I have removed user_id and ext_source_id and I have added ues_id. Table definition to schema.sql was added too.

**Comment by zlamalp** [comment]
Hi, sorry I forgot to mention, please update also DB version in ``test-data.sql`` in perun-core resources (line 2092). Then it can be merged. Thank you.

**Comment by zwejra** [comment]
Done.

**Comment by zwejra** [comment]
Done.

**Pull request merged**
