### PR TITLE
Invite person directly to group

### PR DESCRIPTION
**Pull request by ondrejvelisek**

### CODE REVIEW

**Comment by zlamalp** [comment]
Hi, can you please squash debug commits and create singe one (or multiple if changes are important). Thank you.

**Comment by ondrejvelisek** [comment]
I've squashed it. However wait with merge. (We have to edit settings to already created groups and edit process of approval)

**Comment by zlamalp** [comment]
Hi, can I merge it or you want to fix session expiration refresh as well ? You can make new pull for it if you think this part is done and can be merged.

**Comment by ondrejvelisek** [comment]
Hey. Yes you can merge it but don't forget that somebody have to change settings of already crated groups on production.

**Pull request merged**
