### PR TITLE
feat(core): anonymized attribute added to USER object

### PR DESCRIPTION
**Pull request by Kuliak**
* anonymized attribute added to USER object
* equals, hashcode methods updated for USER
* toString and serializeToString methods updated for both USER and RICHUSER to correctly list all user attributes
* impl layer adjusted to work with newly added attribute (mapping/select)
* openApi USER object updated
* test for anonymizeUser adjusted to check the value of newly added attribute as well

### CODE REVIEW

**Review by Johaney-s — COMMENTED** [review]
looks good to me, please update User and RichUser also in `parseRpcMethods.pl`

**Review by zlamalp — COMMENTED** [review]
Please note, that also other objects extend the User object (like Candidate, CandidateSync). Same objects are also used in API, so we need to test, how it affect de/serialization of them in RPC and old GUI.
For example we should test, if we can create new User/Member from a Candidate through old GUI. Also this might affect synchronization between perun instances (CESNET,MU,Lifescience) - it will fail, if we won't deploy same version on all of them at once. So we might want to make this property optional/ignored in `cz.metacentrum.perun.rpc.deserializer.JsonDeserializer` which is used by API and ExtSourcePerun.

**Comment by Kuliak** [comment]
> Please note, that also other objects extend the User object (like Candidate, CandidateSync). Same objects are also used in API, so we need to test, how it affect de/serialization of them in RPC and old GUI. For example we should test, if we can create new User/Member from a Candidate through old GUI. Also this might affect synchronization between perun instances (CESNET,MU,Lifescience) - it will fail, if we won't deploy same version on all of them at once. So we might want to make this property optional/ignored in `cz.metacentrum.perun.rpc.deserializer.JsonDeserializer` which is used by API and ExtSourcePerun.

Okay, thank you for your feedback! Do you think that _**serviceUser**_ and _**sponsoredUser**_ along with _**anonymized**_ should be added to _**JsonIgnoreProperties**_ for _**UserMixIn**_, or _**anonymized**_ only? It makes sense to me that only _**anonymized**_ will be added there.

**Comment by Johaney-s** [comment]
Solved in https://github.com/CESNET/perun/pull/3785 by creating virtual attribute.

**Pull request closed without merging**
