### PR TITLE
Changes for o365 email modules

### PR DESCRIPTION
**Pull request by stavamichal**
- two new modules has been created for user attributes
 o365UserEmailAddresses:mu and o365SystemEmailAddresses:mu
 - module for attribute o365SystemEmailAddresses:mu checks if all saved
 emails are in correct format and every value of email is unique between
 all saved values of such attributes (between all users in the system)
 - module for attribute o365UserEmailAddresses:mu checks the same syntax
 as o365SystemEmailAddresses:mu and also checks uniqueness of these values
 between all values of attribute group_resource o365EmailAddresses:mu

 - two existing moduels were edited for attributes member
 o365EmailAddresses:mu and group_resource o365EmailAddresses:mu
 - module for attribute member o365EmailAddresses:mu now can have empty
 value (not set value) and checks only format and uniqueness between all
 saved values of this attribute (between all members)
 - in module for attribute group_resource o365EmailAddresses:mu is just
 a minor change in checkAttributeValue method to check uniqueness
 between values of user attribute o365UserEmailAddresses:mu instead of
 member attribute o365EmailAddresses:mu

### CODE REVIEW

**Comment by stavamichal** [comment]
This PR is a replace for existing PR #2105 with more complex logic.

**Comment by zlamalp** [comment]
Just please fix the tests, code logic seem to be ok - relevant for commit message. 
```
[ERROR]   symbol:   variable UCO_ATTRIBUTE
[ERROR]   location: class cz.metacentrum.perun.core.impl.modules.attributes.urn_perun_member_attribute_def_def_o365EmailAddresses_muTest
```

**Comment by stavamichal** [comment]
Fixed.

**Comment by stavamichal** [comment]
Reason of not merging this pull request:
This PR changes logic of working with o365EmailAddresses and need to be merged together with new implementation of user life-cycle in MU by CYCLOP component.
If we merge it before that, we can lose consistency of current user life-cycle.

**Comment by stavamichal** [comment]
PR was rebased to actual master branch.

**Comment by stavamichal** [comment]
Rebased again.

**Comment by stavamichal** [comment]
Because of the change in the logic, this PR will need another review to check if everything is ok.

**Comment by stavamichal** [comment]
PR was rebased to work with migration of attribute gr:d:o365EmailAddresses:mu -> g:d:o365EmailAddresses:o365mu
Also checking of duplicities was removed from attributes that are unique by type of attribute itself.

**Pull request merged**
