### PR TITLE
New workflow for ability to synchronize members by list of their logins

### PR DESCRIPTION
**Pull request by stavamichal**
- new method getGroupSubjects which can get subjects from extSource by
   list of Logins in one or more bulks (not just one by one)
 - redesing of the synchronization process, new method
   categorizeMembersForSynchronization and changes in other methods to
   clear the differences between lightweight and normal synchronization
 - prepare behavior for extSourceSQL and extSourceSQLComplex to be able
   to work with bulk of logins
 - add methods to beansUtils for creating SQLInCaluse for values (not
   just of ids)
 - fix name of method in notification perun module
 - added tests for BeansUtils

### CODE REVIEW

**Comment by stavamichal** [comment]
Rebased version of #1247 
Need to be tested again, lots of minor changes was merged.
I also prefer refactoring of this pull request (commit) to avoid duplicity of code in ExtSourceSql and ExtSourceSqlComplex.

**Comment by stavamichal** [comment]
I re-factored behavior of ExtSourceSQLComplex, now it avoid duplicity of code from ExtSourceSQL.

**Comment by zlamalp** [comment]
Needs rebase, but I would wait after changes with REMS ext source - #1663

**Comment by stavamichal** [comment]
Rebased.

**Pull request closed without merging**
